
package de.dpunkt.myaktion.monitor.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * wsimport.exe -s my-aktion/src/main/java http://localhost:8080/my-aktion-monitor-1.0-SNAPSHOT/SpendeDelegatorService?wsdl
 * Anschliessend wurde Spende.java und Status.java entfernt und die Imports angepasst
 * 
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SpendeDelegatorService", targetNamespace = "http://ws.monitor.myaktion.dpunkt.de/", wsdlLocation = "http://localhost:8080/my-aktion-monitor-1.0-SNAPSHOT/SpendeDelegatorService?wsdl")
public class SpendeDelegatorService
    extends Service
{

    private final static URL SPENDEDELEGATORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.dpunkt.myaktion.monitor.ws.SpendeDelegatorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.dpunkt.myaktion.monitor.ws.SpendeDelegatorService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/my-aktion-monitor-1.0-SNAPSHOT/SpendeDelegatorService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/my-aktion-monitor-1.0-SNAPSHOT/SpendeDelegatorService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SPENDEDELEGATORSERVICE_WSDL_LOCATION = url;
    }

    public SpendeDelegatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SpendeDelegatorService() {
        super(SPENDEDELEGATORSERVICE_WSDL_LOCATION, new QName("http://ws.monitor.myaktion.dpunkt.de/", "SpendeDelegatorService"));
    }

    /**
     * 
     * @return
     *     returns SpendeDelegator
     */
    @WebEndpoint(name = "SpendeDelegatorPort")
    public SpendeDelegator getSpendeDelegatorPort() {
        return super.getPort(new QName("http://ws.monitor.myaktion.dpunkt.de/", "SpendeDelegatorPort"), SpendeDelegator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SpendeDelegator
     */
    @WebEndpoint(name = "SpendeDelegatorPort")
    public SpendeDelegator getSpendeDelegatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.monitor.myaktion.dpunkt.de/", "SpendeDelegatorPort"), SpendeDelegator.class, features);
    }

}
