
package de.dpunkt.myaktion.monitor.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import de.dpunkt.myaktion.model.Spende;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SpendeDelegator", targetNamespace = "http://ws.monitor.myaktion.dpunkt.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SpendeDelegator {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "receiveSpende", targetNamespace = "http://ws.monitor.myaktion.dpunkt.de/", className = "de.dpunkt.myaktion.monitor.ws.ReceiveSpende")
    @ResponseWrapper(localName = "receiveSpendeResponse", targetNamespace = "http://ws.monitor.myaktion.dpunkt.de/", className = "de.dpunkt.myaktion.monitor.ws.ReceiveSpendeResponse")
    public void receiveSpende(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Spende arg1);

}
